# -*- coding:utf-8 -*-
from DingDing.DingDing import DingDing

if __name__ == '__main__':
    dingding = DingDing(secret="secret", url="url")
    result1 = dingding.send_text(content="普通测试")
    print(result1)
    result2 = dingding.send_text(content="测试@全体成员",isAtAll=True)
    print(result2)
    result3 = dingding.send_text(content="测试@指定手机号",atMobiles=["phone1","phone2",...])
    print(result3)
    result4 = dingding.send_link(text="link测试文本", title="link测试标题", pic_url="https://image.biaobaiju.com/uploads/20181007/18/1538909860-QSizdEeDfF.jpg",msg_url="https://news.sina.com.cn/c/xl/2020-08-03/doc-iivhuipn6624743.shtml")
    print(result4)
    result5 = dingding.send_md_string(title="md title",md_text="# md text\n## md text")
    print(result5)
    result6 = dingding.send_md_file(title="md title", md_file_path="DingDing/test.md")
    print(result6)
    result7 = dingding.send_actionCard_all_jump(title="测试actionCard", md_text="# md text", btnOrientation="1", singleTitle="百度", singleURL="https://baidu.com")
    print(result7)
    result8 = dingding.send_actionCard_all_jump_file(title="测试actionCard", md_file="DingDing/test.md", btnOrientation="1", singleTitle="百度", singleURL="https://baidu.com")
    print(result8)
    result9 = dingding.send_actionCard_one_jump(title="测试actionCard", md_text="# md text", btnOrientation="1", **{"否":"https://baidu.com","是":"https://www.mi.com/"})
    print(result9)
    result10 = dingding.send_actionCard_one_jump(title="测试actionCard", md_text="# md text", btnOrientation="0", **{"否":"https://baidu.com","是":"https://www.mi.com/"})
    print(result10)
    result11 = dingding.send_actionCard_one_jump_file(title="测试actionCard", md_file="DingDing/test.md", btnOrientation="0", **{"否": "https://baidu.com", "是": "https://www.mi.com/"})
    print(result11)
    result12 = dingding.send_feedCard(*["title1","http://baidu.com","https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1596471848167&di=4a7db9d732bc9d5d12d48cbf4b2a4ca8&imgtype=0&src=http%3A%2F%2Fdik.img.kttpdq.com%2Fpic%2F142%2F99386%2F5bdc6bc2302e4423_1440x900.jpg","title2","http://www.mi.com","https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1596471848167&di=4a7db9d732bc9d5d12d48cbf4b2a4ca8&imgtype=0&src=http%3A%2F%2Fdik.img.kttpdq.com%2Fpic%2F142%2F99386%2F5bdc6bc2302e4423_1440x900.jpg"])
    print(result12)